export interface CountryInfo {
  code: string;
  name: string;
  flag: string;
  lang: 'en' | 'es' | 'fr' | 'zh' | 'tl' | 'vi' | 'de' | 'it' | 'ja' | 'pt' | 'hi' | 'ar';
}

export const COUNTRIES: CountryInfo[] = [
  { code: 'AF', name: 'Afghanistan', flag: '🇦🇫', lang: 'ar' },
  { code: 'AL', name: 'Albania', flag: '🇦🇱', lang: 'en' },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', lang: 'ar' },
  { code: 'AD', name: 'Andorra', flag: '🇦🇩', lang: 'es' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴', lang: 'pt' },
  { code: 'AG', name: 'Antigua and Barbuda', flag: '🇦🇬', lang: 'en' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', lang: 'es' },
  { code: 'AM', name: 'Armenia', flag: '🇦🇲', lang: 'en' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺 🖤💛❤️', lang: 'en' },
  { code: 'AT', name: 'Austria', flag: '🇦🇹', lang: 'de' },
  { code: 'AZ', name: 'Azerbaijan', flag: '🇦🇿', lang: 'en' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸', lang: 'en' },
  { code: 'BH', name: 'Bahrain', flag: '🇧🇭', lang: 'ar' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', lang: 'en' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧', lang: 'en' },
  { code: 'BY', name: 'Belarus', flag: '🇧🇾', lang: 'en' },
  { code: 'BE', name: 'Belgium', flag: '🇧🇪', lang: 'fr' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿', lang: 'en' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯', lang: 'fr' },
  { code: 'BT', name: 'Bhutan', flag: '🇧🇹', lang: 'en' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴', lang: 'es' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flag: '🇧🇦', lang: 'en' },
  { code: 'BW', name: 'Botswana', flag: '🇧🇼', lang: 'en' },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', lang: 'pt' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳', lang: 'en' },
  { code: 'BG', name: 'Bulgaria', flag: '🇧🇬', lang: 'en' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫', lang: 'fr' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮', lang: 'fr' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻', lang: 'pt' },
  { code: 'KH', name: 'Cambodia', flag: '🇰🇭', lang: 'en' },
  { code: 'CM', name: 'Cameroon', flag: '🇨🇲', lang: 'fr' },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', lang: 'en' },
  { code: 'CF', name: 'Central African Republic', flag: '🇨🇫', lang: 'fr' },
  { code: 'TD', name: 'Chad', flag: '🇹🇩', lang: 'fr' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', lang: 'es' },
  { code: 'CN', name: 'China', flag: '🇨🇳', lang: 'zh' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', lang: 'es' },
  { code: 'KM', name: 'Comoros', flag: '🇰🇲', lang: 'ar' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬', lang: 'fr' },
  { code: 'CD', name: 'DR Congo', flag: '🇨🇩', lang: 'fr' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷', lang: 'es' },
  { code: 'HR', name: 'Croatia', flag: '🇭🇷', lang: 'en' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺', lang: 'es' },
  { code: 'CY', name: 'Cyprus', flag: '🇨🇾', lang: 'en' },
  { code: 'CZ', name: 'Czechia', flag: '🇨🇿', lang: 'en' },
  { code: 'DK', name: 'Denmark', flag: '🇩🇰', lang: 'en' },
  { code: 'DJ', name: 'Djibouti', flag: '🇩🇯', lang: 'fr' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲', lang: 'en' },
  { code: 'DO', name: 'Dominican Republic', flag: '🇩🇴', lang: 'es' },
  { code: 'EC', name: 'Ecuador', flag: '🇪🇨', lang: 'es' },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', lang: 'ar' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻', lang: 'es' },
  { code: 'GQ', name: 'Equatorial Guinea', flag: '🇬🇶', lang: 'es' },
  { code: 'ER', name: 'Eritrea', flag: '🇪🇷', lang: 'en' },
  { code: 'EE', name: 'Estonia', flag: '🇪🇪', lang: 'en' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿', lang: 'en' },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', lang: 'en' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯', lang: 'en' },
  { code: 'FI', name: 'Finland', flag: '🇫🇮', lang: 'en' },
  { code: 'FR', name: 'France', flag: '🇫🇷', lang: 'fr' },
  { code: 'GA', name: 'Gabon', flag: '🇬🇦', lang: 'fr' },
  { code: 'GM', name: 'Gambia', flag: '🇬🇲', lang: 'en' },
  { code: 'GE', name: 'Georgia', flag: '🇬🇪', lang: 'en' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', lang: 'de' },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', lang: 'en' },
  { code: 'GR', name: 'Greece', flag: '🇬🇷', lang: 'en' },
  { code: 'GD', name: 'Grenada', flag: '🇬🇩', lang: 'en' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹', lang: 'es' },
  { code: 'GN', name: 'Guinea', flag: '🇬🇳', lang: 'fr' },
  { code: 'GW', name: 'Guinea-Bissau', flag: '🇬🇼', lang: 'pt' },
  { code: 'GY', name: 'Guyana', flag: '🇬🇾', lang: 'en' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹', lang: 'fr' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳', lang: 'es' },
  { code: 'HU', name: 'Hungary', flag: '🇭🇺', lang: 'en' },
  { code: 'IS', name: 'Iceland', flag: '🇮🇸', lang: 'en' },
  { code: 'IN', name: 'India', flag: '🇮🇳', lang: 'hi' },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', lang: 'en' },
  { code: 'IR', name: 'Iran', flag: '🇮🇷', lang: 'ar' },
  { code: 'IQ', name: 'Iraq', flag: '🇮🇶', lang: 'ar' },
  { code: 'IE', name: 'Ireland', flag: '🇮🇪', lang: 'en' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱', lang: 'en' },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', lang: 'it' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲', lang: 'en' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', lang: 'ja' },
  { code: 'JO', name: 'Jordan', flag: '🇯🇴', lang: 'ar' },
  { code: 'KZ', name: 'Kazakhstan', flag: '🇰🇿', lang: 'en' },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', lang: 'en' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮', lang: 'en' },
  { code: 'KP', name: 'North Korea', flag: '🇰🇵', lang: 'en' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', lang: 'en' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼', lang: 'ar' },
  { code: 'KG', name: 'Kyrgyzstan', flag: '🇰🇬', lang: 'en' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦', lang: 'en' },
  { code: 'LV', name: 'Latvia', flag: '🇱🇻', lang: 'en' },
  { code: 'LB', name: 'Lebanon', flag: '🇱🇧', lang: 'ar' },
  { code: 'LS', name: 'Lesotho', flag: '🇱🇸', lang: 'en' },
  { code: 'LR', name: 'Liberia', flag: '🇱🇷', lang: 'en' },
  { code: 'LY', name: 'Libya', flag: '🇱🇾', lang: 'ar' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮', lang: 'de' },
  { code: 'LT', name: 'Lithuania', flag: '🇱🇹', lang: 'en' },
  { code: 'LU', name: 'Luxembourg', flag: '🇱🇺', lang: 'fr' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬', lang: 'fr' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼', lang: 'en' },
  { code: 'MY', name: 'Malaysia', flag: '🇲🇾', lang: 'en' },
  { code: 'MV', name: 'Maldives', flag: '🇲🇻', lang: 'en' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱', lang: 'fr' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹', lang: 'en' },
  { code: 'MH', name: 'Marshall Islands', flag: '🇲🇭', lang: 'en' },
  { code: 'MR', name: 'Mauritania', flag: '🇲🇷', lang: 'ar' },
  { code: 'MU', name: 'Mauritius', flag: '🇲🇺', lang: 'en' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', lang: 'es' },
  { code: 'FM', name: 'Micronesia', flag: '🇫🇲', lang: 'en' },
  { code: 'MD', name: 'Moldova', flag: '🇲🇩', lang: 'en' },
  { code: 'MC', name: 'Monaco', flag: '🇲🇨', lang: 'fr' },
  { code: 'MN', name: 'Mongolia', flag: '🇲🇳', lang: 'en' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪', lang: 'en' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', lang: 'ar' },
  { code: 'MZ', name: 'Mozambique', flag: '🇲🇿', lang: 'pt' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲', lang: 'en' },
  { code: 'NA', name: 'Namibia', flag: '🇳🇦', lang: 'en' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷', lang: 'en' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵', lang: 'en' },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', lang: 'en' },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', lang: 'en' },
  { code: 'NI', name: 'Nicaragua', flag: '🇳🇮', lang: 'es' },
  { code: 'NE', name: 'Niger', flag: '🇳🇪', lang: 'fr' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', lang: 'en' },
  { code: 'MK', name: 'North Macedonia', flag: '🇲🇰', lang: 'en' },
  { code: 'NO', name: 'Norway', flag: '🇳🇴', lang: 'en' },
  { code: 'OM', name: 'Oman', flag: '🇴🇲', lang: 'ar' },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', lang: 'en' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼', lang: 'en' },
  { code: 'PS', name: 'Palestine', flag: '🇵🇸', lang: 'ar' },
  { code: 'PA', name: 'Panama', flag: '🇵🇦', lang: 'es' },
  { code: 'PG', name: 'Papua New Guinea', flag: '🇵🇬', lang: 'en' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾', lang: 'es' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', lang: 'es' },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', lang: 'tl' },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', lang: 'en' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', lang: 'pt' },
  { code: 'QA', name: 'Qatar', flag: '🇶🇦', lang: 'ar' },
  { code: 'RO', name: 'Romania', flag: '🇷🇴', lang: 'en' },
  { code: 'RU', name: 'Russia', flag: '🇷🇺', lang: 'en' },
  { code: 'RW', name: 'Rwanda', flag: '🇷🇼', lang: 'fr' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flag: '🇰🇳', lang: 'en' },
  { code: 'LC', name: 'Saint Lucia', flag: '🇱🇨', lang: 'en' },
  { code: 'VC', name: 'Saint Vincent', flag: '🇻🇨', lang: 'en' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸', lang: 'en' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲', lang: 'it' },
  { code: 'ST', name: 'Sao Tome and Principe', flag: '🇸🇹', lang: 'pt' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', lang: 'ar' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳', lang: 'fr' },
  { code: 'RS', name: 'Serbia', flag: '🇷🇸', lang: 'en' },
  { code: 'SC', name: 'Seychelles', flag: '🇸🇨', lang: 'fr' },
  { code: 'SL', name: 'Sierra Leone', flag: '🇸🇱', lang: 'en' },
  { code: 'SG', name: 'Singapore', flag: '🇸🇬', lang: 'zh' },
  { code: 'SK', name: 'Slovakia', flag: '🇸🇰', lang: 'en' },
  { code: 'SI', name: 'Slovenia', flag: '🇸🇮', lang: 'en' },
  { code: 'SB', name: 'Solomon Islands', flag: '🇸🇧', lang: 'en' },
  { code: 'SO', name: 'Somalia', flag: '🇸🇴', lang: 'ar' },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', lang: 'en' },
  { code: 'SS', name: 'South Sudan', flag: '🇸🇸', lang: 'en' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', lang: 'es' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰', lang: 'en' },
  { code: 'SD', name: 'Sudan', flag: '🇸🇩', lang: 'ar' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷', lang: 'en' },
  { code: 'SE', name: 'Sweden', flag: '🇸🇪', lang: 'en' },
  { code: 'CH', name: 'Switzerland', flag: '🇨🇭', lang: 'de' },
  { code: 'SY', name: 'Syria', flag: '🇸🇾', lang: 'ar' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼', lang: 'zh' },
  { code: 'TJ', name: 'Tajikistan', flag: '🇹🇯', lang: 'en' },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', lang: 'en' },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', lang: 'en' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱', lang: 'pt' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬', lang: 'fr' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴', lang: 'en' },
  { code: 'TT', name: 'Trinidad and Tobago', flag: '🇹🇹', lang: 'en' },
  { code: 'TN', name: 'Tunisia', flag: '🇹🇳', lang: 'ar' },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', lang: 'en' },
  { code: 'TM', name: 'Turkmenistan', flag: '🇹🇲', lang: 'en' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻', lang: 'en' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', lang: 'en' },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', lang: 'en' },
  { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪', lang: 'ar' },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', lang: 'en' },
  { code: 'US', name: 'United States', flag: '🇺🇸', lang: 'en' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾', lang: 'es' },
  { code: 'UZ', name: 'Uzbekistan', flag: '🇺🇿', lang: 'en' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺', lang: 'en' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪', lang: 'es' },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', lang: 'vi' },
  { code: 'YE', name: 'Yemen', flag: '🇾🇪', lang: 'ar' },
  { code: 'ZM', name: 'Zambia', flag: '🇿🇲', lang: 'en' },
  { code: 'ZW', name: 'Zimbabwe', flag: '🇿🇼', lang: 'en' }
];
