import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '10mb' }));

  // API Routes
  app.post("/api/analyze-report", async (req, res) => {
    try {
      const { image, description } = req.body;
      if (!image) return res.status(400).json({ error: "Image is required" });

      const model = "gemini-3-flash-preview";
      const prompt = `
        Analyze this image of environmental neglect/littering.
        Provide:
        1. A concise category (litter, illegal_dumping, pollution, etc.).
        2. A brief educational tip about the impact of this specific waste.
        3. An "Environmental Impact Score" from 1-10 (10 being most severe).
        4. A short title for the report.
      `;

      const response = await ai.models.generateContent({
        model,
        contents: [
          {
            parts: [
              { text: prompt },
              { inlineData: { mimeType: "image/jpeg", data: image } }
            ]
          }
        ],
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              category: { type: Type.STRING },
              educationalTip: { type: Type.STRING },
              impactScore: { type: Type.NUMBER },
              title: { type: Type.STRING }
            },
            required: ["category", "educationalTip", "impactScore", "title"]
          }
        }
      });

      res.json(JSON.parse(response.text || "{}"));
    } catch (error) {
      console.error("Gemini analysis error:", error);
      res.status(500).json({ error: "Failed to analyze report" });
    }
  });

  app.post("/api/generate-image", async (req, res) => {
    try {
      const { description } = req.body;
      if (!description) return res.status(400).json({ error: "Description is required" });

      const prompt = `A clean, cinematic, high-quality photography style depiction of: ${description}. Theme: Environmental awareness, natural lighting, crisp details, meaningful composition, 4k.`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          imageConfig: {
            aspectRatio: "4:3",
          }
        }
      });

      let imageUrl = "";
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }

      if (!imageUrl) {
        throw new Error("No image generated by model");
      }

      res.json({ imageUrl });
    } catch (error: any) {
      console.error("Gemini image generation error:", error);
      if (error.status === 403 || error.status === 400) {
        res.status(error.status).json({ error: "API Key check required", code: "KEY_ERROR" });
      } else {
        res.status(500).json({ error: "Failed to generate image" });
      }
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
