import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'es' | 'fr' | 'zh' | 'tl' | 'vi';

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'es', name: 'Español', flag: '🇲🇽' },
  { code: 'fr', name: 'Français', flag: '🇨🇦' },
  { code: 'zh', name: '中文 (繁簡)', flag: '🇨🇳' },
  { code: 'tl', name: 'Tagalog', flag: '🇵🇭' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
];

export const translations = {
  en: {
    tosser: "Tosser",
    tagline: "The Environmental Resistance. Swiping for shift.",
    incidentsLogged: "Incidents Logged",
    globalScore: "Global Score",
    home: "Home",
    leader: "Leader",
    profile: "Profile",
    tickerStop: "Stop The Toss",
    tickerAction: "Action = Impact",
    tickerFlagged: "Flagged",
    tickerJoin: "Join the resistance",
    tickerClean: "Keep it clean",
    tickerStopLumping: "Stop Lumping It",
    swipeTitle: "Clean Up Feed",
    awaitingCleanup: "Awaiting Cleanup",
    cleanedSolved: "Cleaned / Solved",
    noLitterLeft: "No Litter Left In Sight!",
    congratulations: "Congratulations, agent! You have cleared this area.",
    pickItUp: "Pick It Up",
    viewProof: "View Proof",
    disposedViewProof: "Disposed • View Proof",
    pickItUpProof: "Pick It Up • Proof",
    takeSelectPhotoProof: "Take/Select Photo Proof",
    submitDisposalProof: "Submit Disposal Proof",
    uploadingProof: "Uploading Proof...",
    approximateLocation: "Approximate Location",
    ecologyAdvisorAlert: "Ecology Advisor Alert",
    reportingAgent: "Reporting Agent",
    resolverAgent: "Resolver Agent",
    awaitingResolution: "Awaiting Resolution",
    beTheAgent: "Be the agent to pick up this litter.",
    pointsRewarded: "points rewarded",
    selectBountyAmount: "Select PayPal Bounty Amount:",
    tipReporter: "Tip Reporter via PayPal",
    bountyResolver: "Bounty Resolver via PayPal",
    yourPaypalLink: "Your Personalized PayPal Link / Email",
    addingPaypalLink: "Adding a PayPal link allows other users to pay or donate to you for picking up and binning their rubbish!",
    reportLitter: "Report Litter Sighting",
    uploadLitterPhoto: "Upload Litter Photo",
    uploadPhotoDesc: "Drag and drop or select photo to begin",
    aiAnalysis: "AI Ecology Advisor Sighting Analysis",
    analyzeLitter: "Analyze Sighting",
    generateDepiction: "Generate Sighting Depiction",
    detectLocation: "Detect My Location",
    selectCity: "Select Near City",
    category: "Category",
    estimatedImpact: "Estimated Impact Score",
    ecologyTip: "Ecology Advisory Tip",
    submitReport: "Log Report Sighting",
    analyzingSighting: "Ecology Advisor analyzing Sighting...",
    generatingDepiction: "Generating depiction...",
    submittingReport: "Logging report...",
    descriptionPlaceholder: "Describe the rubbish, litter, debris or fly-tipping here...",
    yourAgentProfile: "Your Agent Profile",
    editProfile: "Edit Profile",
    saveProfile: "Save Profile",
    agentName: "Agent Name",
    paypalSettings: "PayPal Link / Username",
    cleanupStreak: "Cleanup Streak",
    incentivizingStreak: "Incentivizing environmental action",
    currentStreak: "Current Streak",
    longestStreak: "Longest Streak",
    days: "Days",
    daysMax: "Days Max",
    streakFire: "You are on fire! Pick up more rubbish tomorrow to keep your streak alive!",
    noActiveStreak: "No active streak. Clean up a local waste report today and submit proof to kick off your streak!",
    logout: "Log Out",
    topAgents: "Top Resistance Agents",
    ecoImpactRankings: "Ecology Impact Rankings",
    agentRank: "Rank",
    points: "Points",
    anonymousAgent: "Anonymous Agent",
    totalCleanups: "Total Cleanups",
    viewOnMap: "View On Map",
    activeLitter: "Active Litter",
    cleanedUp: "Cleaned Up",
    descriptionByReporter: "Description by reporter:",
    noDescriptionSupplied: "No description supplied by reporter.",
    involvedAgents: "Involved Agents",
    reporterNoPaypal: "Reporter hasn't linked PayPal yet.",
    resolverNoPaypal: "Resolver hasn't linked PayPal yet.",
    pointsShort: "PTS",
    selectCityLabel: "Geospatial Location Select:",
    orLabel: "OR",
    currentLocationGps: "My Current Location (GPS)",
    coordinates: "Coordinates",
    gpsActive: "GPS Active",
    detectingGps: "Detecting...",
    gpsDetectionFailed: "GPS Failed",
    titlePlaceholder: "Rubbish Title / Tag",
    imageGeneratedAlert: "This image is AI-generated based on description.",
    photoBeforeLabel: "Before (Reported)",
    photoAfterLabel: "After (Picked Up Proof)",
    ecologyAdviceLabel: "Ecology Advisor Alert",
    pickItUpLabel: "Pick It Up!",
    disposalRewardLabel: "Upload visual proof of disposal to claim 50 reward points.",
    howToStreak: "Adding a PayPal link allows other users to pay or donate to you for picking up and binning their rubbish!",
    savingProfileText: "Saving Profile..."
  },
  es: {
    tosser: "Tosser",
    tagline: "La Resistencia Ambiental. Deslizando para el cambio.",
    incidentsLogged: "Incidentes Registrados",
    globalScore: "Puntuación Global",
    home: "Inicio",
    leader: "Líderes",
    profile: "Perfil",
    tickerStop: "Detén la Basura",
    tickerAction: "Acción = Impacto",
    tickerFlagged: "Reportados",
    tickerJoin: "Únete a la resistencia",
    tickerClean: "Mantenlo limpio",
    tickerStopLumping: "No la acumules",
    swipeTitle: "Canal de Limpieza",
    awaitingCleanup: "Esperando Limpieza",
    cleanedSolved: "Limpio / Resuelto",
    noLitterLeft: "¡No queda basura a la vista!",
    congratulations: "¡Felicitaciones, agente! Has despejado esta área.",
    pickItUp: "Recógelo",
    viewProof: "Ver Prueba",
    disposedViewProof: "Desechado • Ver Prueba",
    pickItUpProof: "Recógelo • Prueba",
    takeSelectPhotoProof: "Tomar/Seleccionar Foto de Prueba",
    submitDisposalProof: "Enviar Prueba de Eliminación",
    uploadingProof: "Subiendo Prueba...",
    approximateLocation: "Ubicación Aproximada",
    ecologyAdvisorAlert: "Alerta del Asesor Ecológico",
    reportingAgent: "Agente Reportero",
    resolverAgent: "Agente Solucionador",
    awaitingResolution: "Esperando Resolución",
    beTheAgent: "Sé el agente que recoja esta basura.",
    pointsRewarded: "puntos recompensados",
    selectBountyAmount: "Seleccionar Monto de Recompensa de PayPal:",
    tipReporter: "Dar Propina al Reportero vía PayPal",
    bountyResolver: "Dar Recompensa al Solucionador vía PayPal",
    yourPaypalLink: "Tu Enlace / Correo de PayPal Personalizado",
    addingPaypalLink: "¡Agregar un enlace de PayPal permite que otros usuarios te paguen o donen por recoger y tirar su basura!",
    reportLitter: "Reportar Avistamiento de Basura",
    uploadLitterPhoto: "Subir Foto de Basura",
    uploadPhotoDesc: "Arrastra y suelta o selecciona una foto para comenzar",
    aiAnalysis: "Análisis de Avistamiento del Asesor Ecológico de IA",
    analyzeLitter: "Analizar Avistamiento",
    generateDepiction: "Generar Representación del Avistamiento",
    detectLocation: "Detectar Mi Ubicación",
    selectCity: "Seleccionar Ciudad Cercana",
    category: "Categoría",
    estimatedImpact: "Puntuación de Impacto Estimada",
    ecologyTip: "Consejo de Asesoría Ecológica",
    submitReport: "Registrar Avistamiento de Basura",
    analyzingSighting: "El asesor ecológico está analizando el avistamiento...",
    generatingDepiction: "Generando representación...",
    submittingReport: "Registrando reporte...",
    descriptionPlaceholder: "Describe la basura, desechos, residuos o vertidos ilegales aquí...",
    yourAgentProfile: "Tu Perfil de Agente",
    editProfile: "Editar Perfil",
    saveProfile: "Guardar Perfil",
    agentName: "Nombre del Agente",
    paypalSettings: "Enlace de PayPal / Nombre de Usuario",
    cleanupStreak: "Racha de Limpieza",
    incentivizingStreak: "Incentivando la acción ambiental",
    currentStreak: "Racha Actual",
    longestStreak: "Racha Más Larga",
    days: "Días",
    daysMax: "Días Máx",
    streakFire: "¡Estás en racha! ¡Recoge más basura mañana para mantener viva tu racha de {streak} días!",
    noActiveStreak: "Sin racha activa. ¡Limpia un reporte de desechos local hoy y envía la prueba para comenzar tu racha!",
    logout: "Cerrar Sesión",
    topAgents: "Principales Agentes de la Resistencia",
    ecoImpactRankings: "Clasificación de Impacto Ecológico",
    agentRank: "Rango",
    points: "Puntos",
    anonymousAgent: "Agente Anónimo",
    totalCleanups: "Limpiezas Totales",
    viewOnMap: "Ver En El Mapa",
    activeLitter: "Basura Activa",
    cleanedUp: "Limpio",
    descriptionByReporter: "Descripción del reportero:",
    noDescriptionSupplied: "No se proporcionó descripción.",
    involvedAgents: "Agentes Involucrados",
    reporterNoPaypal: "El reportero aún no ha enlazado PayPal.",
    resolverNoPaypal: "El solucionador aún no ha enlazado PayPal.",
    pointsShort: "PTS",
    selectCityLabel: "Selección de Ubicación Geoespacial:",
    orLabel: "O",
    currentLocationGps: "Mi Ubicación Actual (GPS)",
    coordinates: "Coordenadas",
    gpsActive: "GPS Activo",
    detectingGps: "Detectando...",
    gpsDetectionFailed: "GPS Fallido",
    titlePlaceholder: "Título / Etiqueta de la Basura",
    imageGeneratedAlert: "Esta imagen es generada por IA según la descripción.",
    photoBeforeLabel: "Antes (Reportado)",
    photoAfterLabel: "Después (Prueba de Limpieza)",
    ecologyAdviceLabel: "Consejo del Asesor Ecológico",
    pickItUpLabel: "¡Recógelo!",
    disposalRewardLabel: "Sube una prueba visual de la eliminación para reclamar 50 puntos de recompensa.",
    howToStreak: "¡Agregar un enlace de PayPal permite que otros usuarios te paguen o donen por recoger y depositar la basura en el contenedor!",
    savingProfileText: "Guardando perfil..."
  },
  fr: {
    tosser: "Tosser",
    tagline: "La Résistance Environnementale. Balayez pour le changement.",
    incidentsLogged: "Incidents Signalés",
    globalScore: "Score Global",
    home: "Accueil",
    leader: "Classement",
    profile: "Profil",
    tickerStop: "Arrêtez les Déchets",
    tickerAction: "Action = Impact",
    tickerFlagged: "Signalés",
    tickerJoin: "Rejoignez la résistance",
    tickerClean: "Gardez-le propre",
    tickerStopLumping: "Ne jetez plus",
    swipeTitle: "Flux de Nettoyage",
    awaitingCleanup: "En attente de nettoyage",
    cleanedSolved: "Nettoyé / Résolu",
    noLitterLeft: "Plus aucun déchet en vue !",
    congratulations: "Félicitations, agent ! Vous avez nettoyé cette zone.",
    pickItUp: "Ramassez-le",
    viewProof: "Voir la Preuve",
    disposedViewProof: "Éliminé • Voir la Preuve",
    pickItUpProof: "Ramassez-le • Preuve",
    takeSelectPhotoProof: "Prendre/Sélectionner une Photo de Preuve",
    submitDisposalProof: "Soumettre la Preuve d'Élimination",
    uploadingProof: "Téléchargement de la preuve...",
    approximateLocation: "Localisation Approximative",
    ecologyAdvisorAlert: "Alerte Conseiller Écologie",
    reportingAgent: "Agent Signaleur",
    resolverAgent: "Agent Résolveur",
    awaitingResolution: "En attente de résolution",
    beTheAgent: "Soyez l'agent qui ramasse ce déchet.",
    pointsRewarded: "points récompensés",
    selectBountyAmount: "Sélectionner le montant du don PayPal :",
    tipReporter: "Donner un pourboire au signaleur via PayPal",
    bountyResolver: "Offrir une prime au résolveur via PayPal",
    yourPaypalLink: "Votre lien PayPal / E-mail personnalisé",
    addingPaypalLink: "Ajouter un lien PayPal permet aux autres utilisateurs de vous rémunérer ou de faire un don pour avoir ramassé et jeté leurs déchets !",
    reportLitter: "Signaler un dépôt de déchets",
    uploadLitterPhoto: "Téléverser une photo de déchet",
    uploadPhotoDesc: "Glissez-déposez ou sélectionnez une photo pour commencer",
    aiAnalysis: "Analyse de dépôt du conseiller en écologie IA",
    analyzeLitter: "Analyser le signalement",
    generateDepiction: "Générer une illustration du signalement",
    detectLocation: "Détecter ma position",
    selectCity: "Sélectionner une ville proche",
    category: "Catégorie",
    estimatedImpact: "Score d'impact estimé",
    ecologyTip: "Conseil consultatif d'écologie",
    submitReport: "Enregistrer le signalement",
    analyzingSighting: "Le conseiller en écologie analyse le signalement...",
    generatingDepiction: "Génération de l'illustration...",
    submittingReport: "Enregistrement du rapport...",
    descriptionPlaceholder: "Décrivez les ordures, les détritus, les débris ou les décharges sauvages ici...",
    yourAgentProfile: "Votre Profil d'Agent",
    editProfile: "Modifier le Profil",
    saveProfile: "Sauvegarder le Profil",
    agentName: "Nom de l'Agent",
    paypalSettings: "Lien PayPal / Nom d'utilisateur",
    cleanupStreak: "Série de Nettoyage",
    incentivizingStreak: "Encourager l'action environnementale",
    currentStreak: "Série Actuelle",
    longestStreak: "Meilleure Série",
    days: "Jours",
    daysMax: "Jours Max",
    streakFire: "Vous êtes en feu ! Ramassez d'autres déchets demain pour maintenir votre série de {streak} jours !",
    noActiveStreak: "Aucune série active. Nettoyez un rapport de déchets local aujourd'hui et soumettez la preuve pour démarrer votre série !",
    logout: "Se déconnecter",
    topAgents: "Principaux Agents de la Résistance",
    ecoImpactRankings: "Classement d'Impact Écologique",
    agentRank: "Rang",
    points: "Points",
    anonymousAgent: "Agent Anonyme",
    totalCleanups: "Total des Nettoyages",
    viewOnMap: "Voir Sur La Carte",
    activeLitter: "Déchet Actif",
    cleanedUp: "Nettoyé",
    descriptionByReporter: "Description par le signaleur :",
    noDescriptionSupplied: "Aucune description fournie par le signaleur.",
    involvedAgents: "Agents Impliqués",
    reporterNoPaypal: "Le signaleur n'a pas encore lié son compte PayPal.",
    resolverNoPaypal: "Le résolveur n'a pas encore lié son compte PayPal.",
    pointsShort: "PTS",
    selectCityLabel: "Sélection de l'emplacement géospatial :",
    orLabel: "OU",
    currentLocationGps: "Ma Position Actuelle (GPS)",
    coordinates: "Coordonnées",
    gpsActive: "GPS Activé",
    detectingGps: "Détection...",
    gpsDetectionFailed: "Échec du GPS",
    titlePlaceholder: "Titre / Libellé du déchet",
    imageGeneratedAlert: "Cette image est générée par IA en fonction de la description.",
    photoBeforeLabel: "Avant (Signalé)",
    photoAfterLabel: "Après (Preuve de nettoyage)",
    ecologyAdviceLabel: "Alerte du conseiller en écologie",
    pickItUpLabel: "Ramassez-le !",
    disposalRewardLabel: "Téléversez une preuve visuelle de l'élimination pour réclamer 50 points de récompense.",
    howToStreak: "Ajouter un lien PayPal permet aux autres utilisateurs de vous récompenser ou de faire un don pour avoir ramassé et mis à la poubelle les déchets !",
    savingProfileText: "Enregistrement du profil..."
  },
  zh: {
    tosser: "Tosser",
    tagline: "環境抵抗組織。滑動改變世界。",
    incidentsLogged: "已記錄的垃圾事件",
    globalScore: "全球總分",
    home: "主頁",
    leader: "排行榜",
    profile: "個人檔案",
    tickerStop: "拒絕亂扔垃圾",
    tickerAction: "行動 = 影響",
    tickerFlagged: "已標記",
    tickerJoin: "加入抵抗組織",
    tickerClean: "保持整潔",
    tickerStopLumping: "停止堆積",
    swipeTitle: "清理動態",
    awaitingCleanup: "等待清理",
    cleanedSolved: "已清理 / 已解決",
    noLitterLeft: "視線內沒有垃圾！",
    congratulations: "恭喜你，特工！你已經清除了這個區域的垃圾。",
    pickItUp: "把它撿起來",
    viewProof: "查看證明",
    disposedViewProof: "已處置 • 查看證明",
    pickItUpProof: "把它撿起來 • 證明",
    takeSelectPhotoProof: "拍攝/選擇照片證明",
    submitDisposalProof: "提交處置證明",
    uploadingProof: "正在上傳證明...",
    approximateLocation: "大約位置",
    ecologyAdvisorAlert: "生態顧問警報",
    reportingAgent: "報告特工",
    resolverAgent: "清理特工",
    awaitingResolution: "等待解決",
    beTheAgent: "成為撿起這堆垃圾的特工。",
    pointsRewarded: "積分獎勵",
    selectBountyAmount: "選擇 PayPal 懸賞金額：",
    tipReporter: "透過 PayPal 給報告者小費",
    bountyResolver: "透過 PayPal 給清理者懸賞",
    yourPaypalLink: "您的個性化 PayPal 連結 / 電子郵件",
    addingPaypalLink: "添加 PayPal 連結可讓其他用戶在您撿起並妥善處置垃圾時向您付款或捐款！",
    reportLitter: "報告垃圾發現",
    uploadLitterPhoto: "上傳垃圾照片",
    uploadPhotoDesc: "拖放或選擇照片開始",
    aiAnalysis: "AI 生態顧問發現分析",
    analyzeLitter: "分析發現物",
    generateDepiction: "生成發現物描繪",
    detectLocation: "偵測我的位置",
    selectCity: "選擇附近城市",
    category: "類別",
    estimatedImpact: "估計影響分數",
    ecologyTip: "生態諮詢建議",
    submitReport: "記錄垃圾發現",
    analyzingSighting: "生態顧問正在分析發現物...",
    generatingDepiction: "正在生成描繪...",
    submittingReport: "正在記錄報告...",
    descriptionPlaceholder: "在此描述垃圾、廢棄物、碎片或非法傾倒物...",
    yourAgentProfile: "您的特工檔案",
    editProfile: "編輯檔案",
    saveProfile: "保存檔案",
    agentName: "特工代號",
    paypalSettings: "PayPal 連結 / 用戶名",
    cleanupStreak: "清理連擊",
    incentivizingStreak: "激勵環保行動",
    currentStreak: "當前連擊",
    longestStreak: "最高連擊",
    days: "天",
    daysMax: "天數上限",
    streakFire: "你太棒了！明天繼續撿垃圾以保持你的連續記錄！",
    noActiveStreak: "目前沒有連續記錄。今天清理一處本地廢棄物並提交證明來開始您的連擊吧！",
    logout: "登出",
    topAgents: "頂尖抵抗特工",
    ecoImpactRankings: "生態影響排名",
    agentRank: "排名",
    points: "積分",
    anonymousAgent: "匿名特工",
    totalCleanups: "總清理次數",
    viewOnMap: "在地圖上查看",
    activeLitter: "活動垃圾",
    cleanedUp: "已清理",
    descriptionByReporter: "報告者描述：",
    noDescriptionSupplied: "報告者未提供描述。",
    involvedAgents: "參與特工",
    reporterNoPaypal: "報告者尚未綁定 PayPal。",
    resolverNoPaypal: "清理者尚未綁定 PayPal。",
    pointsShort: "積分",
    selectCityLabel: "地理空間位置選擇：",
    orLabel: "或",
    currentLocationGps: "我的當前位置 (GPS)",
    coordinates: "經緯度坐標",
    gpsActive: "GPS 已啟用",
    detectingGps: "偵測中...",
    gpsDetectionFailed: "GPS 定位失敗",
    titlePlaceholder: "垃圾標題 / 標籤",
    imageGeneratedAlert: "此圖片是根據描述由 AI 生成的。",
    photoBeforeLabel: "前 (報告時)",
    photoAfterLabel: "後 (清理證明)",
    ecologyAdviceLabel: "生態顧問警報",
    pickItUpLabel: "把它撿起來！",
    disposalRewardLabel: "上傳垃圾處置的視覺證明以領取 50 積分獎勵。",
    howToStreak: "添加 PayPal 連結可讓其他用戶在您撿起並處置垃圾時向您支付小費或捐款！",
    savingProfileText: "正在保存個人檔案..."
  },
  tl: {
    tosser: "Tosser",
    tagline: "Ang Paglaban sa Kalikasan. Pag-swipe para sa pagbabago.",
    incidentsLogged: "Mga Naitalang Pangyayari",
    globalScore: "Pandaigdigang Iskor",
    home: "Home",
    leader: "Leaderboard",
    profile: "Profile",
    tickerStop: "Ihinto ang Pagkakalat",
    tickerAction: "Aksyon = Epekto",
    tickerFlagged: "Na-flag",
    tickerJoin: "Sumali sa paglaban",
    tickerClean: "Panatilihing malinis",
    tickerStopLumping: "Huwag i-tambak",
    swipeTitle: "Feed ng Paglilinis",
    awaitingCleanup: "Naghihintay ng Paglilinis",
    cleanedSolved: "Nalinis / Nalutas na",
    noLitterLeft: "Wala nang basura sa paningin!",
    congratulations: "Congratulations, agent! Nalinisan mo ang lugar na ito.",
    pickItUp: "Pulutin Ito",
    viewProof: "Tingnan ang Katunayan",
    disposedViewProof: "Naitapon • Tingnan ang Katunayan",
    pickItUpProof: "Pulutin Ito • Katunayan",
    takeSelectPhotoProof: "Kumuha/Pumili ng Larawan bilang Katunayan",
    submitDisposalProof: "Isumite ang Katunayan ng Pagtatapon",
    uploadingProof: "Ina-upload ang katunayan...",
    approximateLocation: "Tinatayang Lokasyon",
    ecologyAdvisorAlert: "Babala ng Tagapayo sa Ekolohiya",
    reportingAgent: "Nag-ulat na Agent",
    resolverAgent: "Lumutas na Agent",
    awaitingResolution: "Naghihintay ng Resolusyon",
    beTheAgent: "Maging agent na pupulot sa basurang ito.",
    pointsRewarded: "puntos na iginawad",
    selectBountyAmount: "Pumili ng Halaga ng PayPal Bounty:",
    tipReporter: "Mag-tip sa Nag-ulat gamit ang PayPal",
    bountyResolver: "Bounty para sa Lumutas gamit ang PayPal",
    yourPaypalLink: "Iyong Personalized PayPal Link / Email",
    addingPaypalLink: "Ang pagdaragdag ng PayPal link ay nagpapahintulot sa ibang user na bayaran o bigyan ka ng donasyon sa pagpulot at pagtapon ng basura!",
    reportLitter: "Iulat ang Nakitang Basura",
    uploadLitterPhoto: "I-upload ang Larawan ng Basura",
    uploadPhotoDesc: "I-drag at i-drop o pumili ng larawan para magsimula",
    aiAnalysis: "Pagsusuri ng AI Ecology Advisor sa Nakitang Basura",
    analyzeLitter: "Suriin ang Nakita",
    generateDepiction: "Gumawa ng Depiksyon ng Nakita",
    detectLocation: "Tukuyin ang Aking Lokasyon",
    selectCity: "Pumili ng Malapit na Lungsod",
    category: "Kategorya",
    estimatedImpact: "Tinatayang Iskor ng Epekto",
    ecologyTip: "Payo sa Ekolohiya",
    submitReport: "I-log ang Nakitang Basura",
    analyzingSighting: "Sinusuri ng Ecology Advisor ang nakitang basura...",
    generatingDepiction: "Gumagawa ng depiksyon...",
    submittingReport: "Inililista ang ulat...",
    descriptionPlaceholder: "Ilarawan ang basura, kalat, o ilegal na pagtatapon dito...",
    yourAgentProfile: "Iyong Agent Profile",
    editProfile: "I-edit ang Profile",
    saveProfile: "I-save ang Profile",
    agentName: "Pangalan ng Agent",
    paypalSettings: "PayPal Link / Username",
    cleanupStreak: "Streak ng Paglilinis",
    incentivizingStreak: "Hinihikayat ang pagkilos para sa kalikasan",
    currentStreak: "Kasalukuyang Streak",
    longestStreak: "Pinakamahabang Streak",
    days: "Araw",
    daysMax: "Max na Araw",
    streakFire: "Nagliliyab ka! Pulutin ang iba pang basura bukas upang mapanatili ang iyong {streak}-araw na streak!",
    noActiveStreak: "Walang aktibong streak. Maglinis ng ulat ng basura ngayon at magsumite ng katunayan para magsimula ng iyong streak!",
    logout: "Mag-log Out",
    topAgents: "Mga Nangungunang Agent ng Paglaban",
    ecoImpactRankings: "Mga Ranggo ng Epekto sa Ekolohiya",
    agentRank: "Ranggo",
    points: "Puntos",
    anonymousAgent: "Anonymous Agent",
    totalCleanups: "Kabuuang Paglilinis",
    viewOnMap: "Tingnan sa Mapa",
    activeLitter: "Aktibong Basura",
    cleanedUp: "Nalinis Na",
    descriptionByReporter: "Paglalarawan ng nag-ulat:",
    noDescriptionSupplied: "Walang ibinigay na paglalarawan ang nag-ulat.",
    involvedAgents: "Mga Kasangkot na Agent",
    reporterNoPaypal: "Hindi pa nagli-link ng PayPal ang nag-ulat.",
    resolverNoPaypal: "Hindi pa nagli-link ng PayPal ang lumutas.",
    pointsShort: "PTS",
    selectCityLabel: "Pagpili ng Geospatial na Lokasyon:",
    orLabel: "O",
    currentLocationGps: "Aking Kasalukuyang Lokasyon (GPS)",
    coordinates: "Mga Coordinate",
    gpsActive: "Aktibo ang GPS",
    detectingGps: "Tinu-tukoy...",
    gpsDetectionFailed: "Bigo ang GPS",
    titlePlaceholder: "Pamagat / Tag ng Basura",
    imageGeneratedAlert: "Ang larawang ito ay gawa ng AI base sa paglalarawan.",
    photoBeforeLabel: "Bago (Iniulat)",
    photoAfterLabel: "Pagkatapos (Nalinis na Katunayan)",
    ecologyAdviceLabel: "Babala ng Tagapayo sa Ekolohiya",
    pickItUpLabel: "Pulutin Ito!",
    disposalRewardLabel: "I-upload ang visual na katunayan ng pagtatapon para makakuha ng 50 reward points.",
    howToStreak: "Ang pagdaragdag ng PayPal link ay nagpapahintulot sa ibang user na bayaran o bigyan ka ng donasyon sa pagpulot at pagtapon ng basura!",
    savingProfileText: "Inise-save ang Profile..."
  },
  vi: {
    tosser: "Tosser",
    tagline: "Kháng Chiến Môi Trường. Vuốt để thay đổi.",
    incidentsLogged: "Sự Cố Đã Ghi Nhận",
    globalScore: "Điểm Toàn Cầu",
    home: "Trang Chủ",
    leader: "Xếp Hạng",
    profile: "Hồ Sơ",
    tickerStop: "Ngừng Xả Rác",
    tickerAction: "Hành Động = Tác Động",
    tickerFlagged: "Đã Đánh Dấu",
    tickerJoin: "Gia nhập lực lượng",
    tickerClean: "Giữ sạch sẽ",
    tickerStopLumping: "Đừng tích tụ",
    swipeTitle: "Bản Tin Dọn Dẹp",
    awaitingCleanup: "Đang Chờ Dọn Dẹp",
    cleanedSolved: "Đã Dọn / Đã Giải Quyết",
    noLitterLeft: "Không còn rác trong tầm mắt!",
    congratulations: "Chúc mừng đặc vụ! Bạn đã làm sạch khu vực này.",
    pickItUp: "Nhặt Lên Ngay",
    viewProof: "Xem Minh Chứng",
    disposedViewProof: "Đã Xử Lý • Xem Minh Chứng",
    pickItUpProof: "Nhặt Lên • Minh Chứng",
    takeSelectPhotoProof: "Chụp/Chọn Ảnh Minh Chứng",
    submitDisposalProof: "Gửi Minh Chứng Xử Lý",
    uploadingProof: "Đang tải minh chứng...",
    approximateLocation: "Vị Trí Ước Tính",
    ecologyAdvisorAlert: "Cảnh Báo Cố Vấn Sinh Thái",
    reportingAgent: "Đặc Vụ Báo Cáo",
    resolverAgent: "Đặc Vụ Giải Quyết",
    awaitingResolution: "Chờ Giải Quyết",
    beTheAgent: "Hãy là đặc vụ nhặt sạch bãi rác này.",
    pointsRewarded: "điểm thưởng",
    selectBountyAmount: "Chọn Số Tiền Thưởng PayPal:",
    tipReporter: "Tặng Tiền Cho Người Báo Cáo qua PayPal",
    bountyResolver: "Tặng Thưởng Cho Người Dọn Dẹp qua PayPal",
    yourPaypalLink: "Liên Kết / Email PayPal Cá Nhân Của Bạn",
    addingPaypalLink: "Thêm liên kết PayPal cho phép người dùng khác trả tiền hoặc quyên góp cho bạn vì đã nhặt và vứt rác đúng nơi quy định!",
    reportLitter: "Báo Cáo Phát Hiện Rác",
    uploadLitterPhoto: "Tải Ảnh Rác Lên",
    uploadPhotoDesc: "Kéo thả hoặc chọn ảnh để bắt đầu",
    aiAnalysis: "Phân Tích Phát Hiện Từ Cố Vấn Sinh Thái AI",
    analyzeLitter: "Phân Tích Phát Hiện",
    generateDepiction: "Tạo Hình Ảnh Mô Tả",
    detectLocation: "Xác Định Vị Trí Của Tôi",
    selectCity: "Chọn Thành Phố Lân Cận",
    category: "Danh mục",
    estimatedImpact: "Điểm Tác Động Ước Tính",
    ecologyTip: "Lời Khuyên Sinh Thái",
    submitReport: "Ghi Nhận Phát Hiện Rác",
    analyzingSighting: "Cố vấn sinh thái đang phân tích phát hiện...",
    generatingDepiction: "Đang tạo hình ảnh mô tả...",
    submittingReport: "Đang lưu báo cáo...",
    descriptionPlaceholder: "Mô tả rác thải, phế liệu hoặc đổ trộm tại đây...",
    yourAgentProfile: "Hồ Sơ Đặc Vụ",
    editProfile: "Chỉnh Sửa Hồ Sơ",
    saveProfile: "Lưu Hồ Sơ",
    agentName: "Tên Đặc Vụ",
    paypalSettings: "Liên Kết PayPal / Tên Người Dùng",
    cleanupStreak: "Chuỗi Ngày Dọn Dẹp",
    incentivizingStreak: "Khuyến khích hành động bảo vệ môi trường",
    currentStreak: "Chuỗi Hiện Tại",
    longestStreak: "Chuỗi Kỷ Lục",
    days: "Ngày",
    daysMax: "Ngày Tối Đa",
    streakFire: "Bạn đang bùng cháy! Hãy dọn dẹp thêm rác vào ngày mai để duy trì chuỗi {streak} ngày của bạn!",
    noActiveStreak: "Không có chuỗi hoạt động. Hãy dọn dẹp rác thải địa phương hôm nay và gửi minh chứng để bắt đầu chuỗi ngày của bạn!",
    logout: "Đăng Xuất",
    topAgents: "Đặc Vụ Kháng Chiến Hàng Đầu",
    ecoImpactRankings: "Bảng Xếp Hạng Tác Động Sinh Thái",
    agentRank: "Hạng",
    points: "Điểm",
    anonymousAgent: "Đặc Vụ Ẩn Danh",
    totalCleanups: "Tổng Số Lượt Dọn",
    viewOnMap: "Xem Trên Bản Đồ",
    activeLitter: "Rác Hoạt Động",
    cleanedUp: "Đã Dọn Sạch",
    descriptionByReporter: "Mô tả từ người báo cáo:",
    noDescriptionSupplied: "Người báo cáo không cung cấp mô tả.",
    involvedAgents: "Các Đặc Vụ Liên Quan",
    reporterNoPaypal: "Người báo cáo chưa liên kết PayPal.",
    resolverNoPaypal: "Người dọn dẹp chưa liên kết PayPal.",
    pointsShort: "ĐIỂM",
    selectCityLabel: "Chọn Vị Trí Địa Lý:",
    orLabel: "HOẶC",
    currentLocationGps: "Vị Trí Hiện Tại Của Tôi (GPS)",
    coordinates: "Tọa Độ",
    gpsActive: "GPS Đang Hoạt Động",
    detectingGps: "Đang xác định...",
    gpsDetectionFailed: "Lỗi GPS",
    titlePlaceholder: "Tiêu Đề / Nhãn Rác",
    imageGeneratedAlert: "Hình ảnh này được tạo bởi AI dựa trên mô tả.",
    photoBeforeLabel: "Trước (Báo Cáo)",
    photoAfterLabel: "Sau (Minh Chứng Dọn Dẹp)",
    ecologyAdviceLabel: "Cảnh báo từ Cố vấn Sinh thái",
    pickItUpLabel: "Nhặt Lên Ngay!",
    disposalRewardLabel: "Tải minh chứng dọn dẹp thực tế lên để nhận 50 điểm thưởng.",
    howToStreak: "Thêm liên kết PayPal cho phép người dùng khác thanh toán hoặc quyên góp cho bạn vì đã thu gom rác!",
    savingProfileText: "Đang lưu hồ sơ..."
  }
};

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: keyof typeof translations['en'], params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>('en');

  useEffect(() => {
    // Detect browser language or default to English
    const storedLang = localStorage.getItem('tosser_language') as LanguageCode;
    if (storedLang && translations[storedLang]) {
      setLanguageState(storedLang);
    } else {
      const browserLang = navigator.language.split('-')[0] as LanguageCode;
      if (browserLang && translations[browserLang]) {
        setLanguageState(browserLang);
      }
    }
  }, []);

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('tosser_language', lang);
  };

  const t = (key: keyof typeof translations['en'], params?: Record<string, any>): string => {
    const translationSet = translations[language] || translations['en'];
    let text = translationSet[key] || translations['en'][key] || String(key);

    if (params) {
      Object.keys(params).forEach((paramKey) => {
        text = text.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
